vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    recipe_images:
      uri_prefix: '%recipe_images%'
      upload_destination: '%kernel.project_dir%/public%recipe_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
# Vich uploader Bundle permet de mettre en place un systeme d'upload d'images
